PrintConfig = false
[http]
    [http.mgr]
        addr = ":3223"
        mod = "test"
    [http.api]
        addr = ":3323"
        mod = "test"
[log]
    dir = "/Users/liangpang/Documents/go/sscmgroup.com/logs"
    FileName = "sscmgroup.log"
    Level = "debug"
[databases]
    [databases.mgr_db]
        driver = "mysql"
        dsn = "root:@tcp(127.0.0.1:3306)/gin_casbin_test?parseTime=True&loc=Local&allowNativePasswords=true"
        active = 1000
        idle = 10
        idleTimeout = 10
    [databases.cms_db]
        driver = "mysql"
        dsn = "root:@tcp(127.0.0.1:3306)/gin_casbin_test?parseTime=True&loc=Local&allowNativePasswords=true"
        active = 1000
        idle = 10
        idleTimeout = 10
[casbin]
    Enable = true
    Debug = true
    Model = "/Users/liangpang/Documents/go/sscmgroup.com/conf/model.conf"
    AutoLoad = true
    AutoLoadInternal = 60
[jwt]
    [jwt.user]
        secret = "g1zUtXcZY38zX6SlvdySbKdivqvBdre8"
        ttl = 2592000
[redis]
    [redis.user_cache]
        addrs = "127.0.0.1:6379"
        password = ""
        pool_size = 100
    [redis.book_cache]
        addrs = "127.0.0.1:6379"
        password = ""
        pool_size = 100
[captcha]
    # 存储方式(支持：memory/redis)
    Store = "memory"
    # 数字长度
    Length = 8
    # 图片宽度
    Width = 400
    # 图片高度
    Height = 160
    # redis数据库(如果存储方式是redis，则指定存储的数据库)
    RedisDB = 10
    # 存储到redis数据库中的键名前缀
    RedisPrefix = "captcha_"
    ttl = 60